version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:12
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "4000:4000"
    volumes:
      - .:/home/node/charesapi
      - node_modules:/home/node/charesapi/node_modules
    networks:
      - app-network
    depends_on:
      - "db"
    command:
      [
        "./wait-for-it.sh",
        "db:27017",
        "--",
        "/home/node/charesapi/node_modules/.bin/nodemon",
        "./src/server.js",
      ]

  db:
    image: mongo:4.2
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE:CharesAPI
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - 27017:27017
    networks:
      - app-network
    volumes:
      - /usr/local/var/mongodb:/data/db
      - name:/usr/local/var/mongodb

networks:
  app-network:
    driver: bridge
volumes:
  node_modules:
  name:
